# Generated by Django 5.1.1 on 2025-07-03 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorAppoinment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorname', models.CharField(max_length=255)),
                ('timeslot', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserAppoinment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('phoneno', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('doctorname', models.CharField(max_length=255)),
                ('timeslot', models.DateTimeField()),
                ('symptoms', models.TextField()),
            ],
        ),
    ]
